@startuml

entity Cliente{
    PK Long id
    FK Long id_ubicacion
    Int cantidad_pedidos_realizados
    varchar(255) nombre
    varchar(255) apellido
    varchar(255) email
    varchar(255) telefono
    date fecha_nacimiento
}

entity Pedido{
    PK Long id
    FK Long id_cliente
    FK Long id_mercaderia
    FK Long id_direccion_entrega
    FK Long id_deposito
    Boolean es_entrega_a_direccion
    Float cantidad
    Float peso_total
    Varchar(255) estado
    Date fecha_pedido
    Boolean entregado
    Date fecha_entrega
}

entity Mercaderia{
    FK Long id
    varchar(255) nombre
    varchar(255) descripcion
    Float peso
    Float precio
}


entity Entrega{
    FK Long id
    FK Long id_pedido
    FK Long id_cliente
    FK Long id_ubicacion
    Date fecha_entrega
    Boolean estado
}


entity Ubicacion{
    FK Long id
    varchar(255) calle
    varchar(255) numero
    varchar(255) localidad
    varchar(255) provincia
    varchar(255) pais
    varchar(255) codigo_postal
    varchar(255) descripcion
}

entity Deposito{
    FK Long id
    FK Long id_ubicacion
    varchar(255) nombre
    varchar(255) descripcion
}

entity Empleado{
    PK Long id
    varchar(255) nombre
    varchar(255) apellido
    varchar(255) email
    varchar(255) telefono
    date fecha_nacimiento
}

entity Ventas{
    PK Long id
    FK Long id_pedido
    FK Long id_empleado
    FK Long id_cliente
}

entity Mercaderia_x_pedido{
PK Long id
    FK Long id_pedido
    FK Long id_mercaderia
    Float cantidad
    Float peso_total
}

entity Entrega_x_pedido{
    PK Long id
    FK Long id_pedido
    FK Long id_entrega
}

Cliente ||--|| Ubicacion
Cliente ||--o{ Pedido

Mercaderia ||--|{ Mercaderia_x_pedido

Pedido ||--|{ Mercaderia_x_pedido
Pedido }o--|| Deposito
Pedido ||--|| Ubicacion
Pedido ||--o{ Entrega_x_pedido

Ventas ||--|{ Cliente
Ventas }o--|| Pedido

Empleado ||--o{ Ventas
Entrega ||--o{ Entrega_x_pedido

Deposito ||--|| Ubicacion

@enduml

Entity01 }|..|| Entity02
Entity03 }o..o| Entity04
Entity05 ||--o{ Entity06
Entity07 |o--|| Entity08

entity Envio{
    PK Long id
    FK Long id_pedido
    Varchar(255) estado
}